export const kneeModalContent = {
  main: {
    title: "Total Knee Replacement",
    description: "Explore comprehensive information about knee replacement surgery, implant choices, recovery, and what to expect.",
    sections: [
      { label: "Surgery Types", key: "surgeryTypes" },
      { label: "Implant Brands", key: "implantBrands" },
      { label: "How to Choose", key: "chooseImplant" },
      { label: "Before & After", key: "beforeAfter" },
    ],
  },
  surgeryTypes: {
    title: "Types of Knee Replacement Surgery",
    parent: "main",
    description: "Six different surgical approaches tailored to your condition",
    items: [
      { id: "total", name: "Total Knee Replacement", preview: "Most common surgery in India", key: "totalKnee" },
      { id: "partial", name: "Partial Knee Replacement", preview: "One compartment only", key: "partialKnee" },
      { id: "revision", name: "Revision Knee Replacement", preview: "Worn implant replacement", key: "revisionKnee" },
      { id: "bilateral", name: "Bilateral Knee Replacement", preview: "Both knees simultaneously", key: "bilateralKnee" },
      { id: "patellofemoral", name: "Patellofemoral Replacement", preview: "Kneecap and thighbone only", key: "patellofemoralKnee" },
    ],
  },
  implantBrands: {
    title: "Internationally Trusted Implant Brands",
    parent: "main",
    description: "Premium knee implant systems used by Dr. Nishant Verma",
    items: [
      { id: "zimmer", name: "Zimmer Biomet (USA)", preview: "Persona & NexGen systems", key: "zimmerDetail" },
      { id: "maxx", name: "Maxx Orthopedics (USA)", preview: "Freedom® Knee System", key: "maxxDetail" },
      { id: "depuy", name: "DePuy Synthes (Johnson & Johnson)", preview: "Attune® Knee System", key: "depuyDetail" },
      { id: "microport", name: "MicroPort Orthopedics", preview: "Evolution® Knee System", key: "microportDetail" },
      { id: "stryker", name: "StryKer", preview: "Triathlon Knee System", key: "strykerDetail" },
    ],
  },
  chooseImplant: {
    title: "How Dr. Nishant Chooses Your Implant",
    parent: "main",
    description: "Personalized implant selection based on your unique factors",
    items: [
      { id: "age", name: "Age & Activity Level", preview: "Different needs for different ages", key: "ageDetail" },
      { id: "severity", name: "Severity of Knee Damage", preview: "Assessment of arthritis level", key: "severityDetail" },
      { id: "bone", name: "Bone Quality & Alignment", preview: "Structural assessment", key: "boneDetail" },
      { id: "lifestyle", name: "Lifestyle & Daily Activity", preview: "Activity-specific implants", key: "lifestyleDetail" },
      { id: "material", name: "Implant Material & Technology", preview: "Advanced materials & design", key: "materialDetail" },
    ],
  },
  beforeAfter: {
    title: "Before & After Surgery",
    parent: "main",
    description: "What to expect before, during, and after your procedure",
    items: [
      { id: "before", name: "Before Surgery", preview: "Preparation & evaluation", key: "beforeDetail" },
      { id: "procedure", name: "The Procedure", preview: "Surgical steps explained", key: "procedureDetail" },
      { id: "recovery", name: "Recovery & Rehabilitation", preview: "Post-surgery care plan", key: "recoveryDetail" },
      { id: "complications", name: "Possible Complications", preview: "What to watch for", key: "complicationsDetail" },
    ],
  },
  totalKnee: {
    title: "Total Knee Replacement Surgery",
    parent: "surgeryTypes",
    image: "https://images.unsplash.com/photo-1579154204601-01d82f3b80c8?w=600&h=400&fit=crop&q=80",
    content: `<h3 style="color: #2D8C7F; margin-bottom: 1rem;">Most Common Knee Surgery</h3><p>Total knee replacement is the most common orthopedic procedure in India. The surgeon replaces the damaged knee joint with artificial implants made of metal and plastic.</p><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">Procedure Steps</h4><ul style="list-style: none; padding: 0;"><li style="margin-bottom: 0.8rem; padding-left: 1.5rem;"><strong>1. Prepare the skeleton</strong> - Remove damaged cartilage and bone</li><li style="margin-bottom: 0.8rem; padding-left: 1.5rem;"><strong>2. Arrange metal implants</strong> - Metal components are cemented or press-fitted</li><li style="margin-bottom: 0.8rem; padding-left: 1.5rem;"><strong>3. Recondition kneecap</strong> - Cover undersurface with plastic button</li><li style="margin-bottom: 0.8rem; padding-left: 1.5rem;"><strong>4. Place separator</strong> - Medical-grade plastic creates smooth sliding surface</li></ul><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">Success Rate</h4><p>Less than 2% of patients experience complications. High success rate with long-lasting results.</p><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">Hospital Stay</h4><p>3-5 days for observation and initial recovery. Full recovery: 3-6 months.</p>`,
  },
  partialKnee: {
    title: "Partial Knee Replacement",
    parent: "surgeryTypes",
    image: "https://images.unsplash.com/photo-1576091160550-112173f7f869?w=600&h=400&fit=crop&q=80",
    content: `<h3 style="color: #2D8C7F; margin-bottom: 1rem;">Single Compartment Surgery</h3><p>When only one compartment of your knee is damaged, the surgeon replaces only that part. Your healthy compartments remain unchanged.</p><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">Benefits</h4><ul style="list-style: none; padding: 0;"><li>Faster healing than total knee replacement</li><li>Easier to get back on your feet</li><li>Less pain and swelling post-operation</li></ul><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">Recovery Time</h4><p>Shorter recovery period. Most patients return to activities quicker than total replacement.</p>`,
  },
  revisionKnee: {
    title: "Revision Knee Replacement",
    parent: "surgeryTypes",
    image: "https://images.unsplash.com/photo-1631217314830-4d4b2f32c147?w=600&h=400&fit=crop&q=80",
    content: `<h3 style="color: #2D8C7F; margin-bottom: 1rem;">When Implants Need Replacement</h3><p>Like any implant, knee replacements can wear out after 15-20+ years. Revision surgery replaces the worn components.</p><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">Two Types of Revision</h4><div style="background: #f7f9f8; padding: 1rem; border-radius: 8px; margin-bottom: 1rem;"><h5 style="color: #2D8C7F;">1. Single-Stage Revision</h5><p>Old implant removed and new one inserted in same operation.</p></div><div style="background: #f7f9f8; padding: 1rem; border-radius: 8px;"><h5 style="color: #2D8C7F;">2. Two-Stage Revision</h5><p>Used for joint infections. Remove implant, insert spacer, then new implant after infection clears.</p></div><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">Recovery</h4><p>4-7 days hospital rest. Complete recovery: 3-6 months with physiotherapy.</p>`,
  },
  bilateralKnee: {
    title: "Bilateral Knee Replacement",
    parent: "surgeryTypes",
    image: "https://images.unsplash.com/photo-1576091160550-112173f7f869?w=600&h=400&fit=crop&q=80",
    content: `<h3 style="color: #2D8C7F; margin-bottom: 1rem;">Replacing Both Knees</h3><p>When both knees are severely damaged, Dr. Nishant Verma may perform bilateral replacement simultaneously or in separate surgeries.</p><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">Who Needs This Surgery?</h4><ul style="list-style: none; padding: 0;"><li>Severe pain in both knees affecting daily life</li><li>Difficulty walking, climbing stairs, or standing</li><li>Other treatments failed (medication, PT, injections)</li><li>X-rays show severe joint damage in both knees</li></ul><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">Recovery Timeline</h4><p><strong>Hospital Stay:</strong> 3-7 days | <strong>Full Recovery:</strong> 3-6 months</p>`,
  },
  patellofemoralKnee: {
    title: "Patellofemoral Replacement",
    parent: "surgeryTypes",
    image: "https://images.unsplash.com/photo-1631217314830-4d4b2f32c147?w=600&h=400&fit=crop&q=80",
    content: `<h3 style="color: #2D8C7F; margin-bottom: 1rem;">Kneecap & Thighbone Only</h3><p>This specialized surgery targets only the joint where the kneecap meets the thighbone.</p><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">Success & Recovery</h4><p><strong>Success Rate:</strong> 80-90% | <strong>Implant Lifespan:</strong> 10-15+ years</p><p><strong>Recovery Timeline:</strong> Can walk in 24-48 hours | Return to activities in 2-6 weeks | Full recovery in 3-6 months</p>`,
  },
  zimmerDetail: {
    title: "Zimmer Biomet (USA)",
    parent: "implantBrands",
    image: "https://images.unsplash.com/photo-1576091160550-112173f7f869?w=600&h=400&fit=crop&q=80",
    content: `<h3 style="color: #2D8C7F; margin-bottom: 1rem;">Global Leader in Joint Solutions</h3><p>Zimmer Biomet provides proven solutions for joint problems. Their implants help patients move better and live pain-free lives.</p><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">Featured Systems</h4><div style="background: #f7f9f8; padding: 1rem; border-radius: 8px; margin-bottom: 1rem;"><h5 style="color: #2D8C7F;">Persona® Knee System</h5><p>Advanced design for natural knee movement.</p></div><div style="background: #f7f9f8; padding: 1rem; border-radius: 8px;"><h5 style="color: #2D8C7F;">NexGen® Knee System</h5><p>Proven long-term performance trusted worldwide.</p></div>`,
  },
  maxxDetail: {
    title: "Maxx Orthopedics - Freedom® Knee System",
    parent: "implantBrands",
    image: "https://images.unsplash.com/photo-1579154204601-01d82f3b80c8?w=600&h=400&fit=crop&q=80",
    content: `<h3 style="color: #2D8C7F; margin-bottom: 1rem;">High-Flexion Movement Design</h3><p>The Freedom® Knee System is engineered for patients who want to stay active. It mimics natural knee movement for improved function.</p><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">Key Features</h4><ul style="list-style: none; padding: 0;"><li>High-Flexion Movement for active patients</li><li>Range of Motion & Stability</li><li>Natural Movement Pattern</li><li>Cost-Effective quality technology</li></ul>`,
  },
  depuyDetail: {
    title: "DePuy Synthes - Attune® Knee System",
    parent: "implantBrands",
    image: "https://images.unsplash.com/photo-1579154204601-01d82f3b80c8?w=600&h=400&fit=crop&q=80",
    content: `<h3 style="color: #2D8C7F; margin-bottom: 1rem;">Johnson & Johnson Innovation</h3><p>DePuy Synthes combines research expertise with advanced engineering to create the Attune® Knee System.</p><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">Why Surgeons Trust Attune®</h4><ul style="list-style: none; padding: 0;"><li>Mimics natural knee movement</li><li>Strong track record</li><li>Reliable results</li><li>High patient satisfaction</li></ul>`,
  },
  microportDetail: {
    title: "MicroPort Orthopedics - Evolution® Knee System",
    parent: "implantBrands",
    image: "https://images.unsplash.com/photo-1631217314830-4d4b2f32c147?w=600&h=400&fit=crop&q=80",
    content: `<h3 style="color: #2D8C7F; margin-bottom: 1rem;">Cutting-Edge Asian Innovation</h3><p>MicroPort is renowned for joint replacement excellence with continuous investment in research and technology.</p><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">Evolution® Knee System</h4><ul style="list-style: none; padding: 0;"><li>Natural Movement - mimics real knee biomechanics</li><li>Strong & Sturdy - feels stable after surgery</li><li>Easy Mobility - get back on your feet quickly</li><li>Long-Lasting - solid durability record</li></ul>`,
  },
  strykerDetail: {
    title: "StryKer - Triathlon Knee System",
    parent: "implantBrands",
    image: "https://images.unsplash.com/photo-1576091160550-112173f7f869?w=600&h=400&fit=crop&q=80",
    content: `<h3 style="color: #2D8C7F; margin-bottom: 1rem;">High-Performance Medical Technology</h3><p>Stryker stands out as a top medical technology company with leadership in joint replacement.</p><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">Triathlon Knee System Features</h4><ul style="list-style: none; padding: 0;"><li>Works Like a Real Knee - mimics natural biomechanics</li><li>Very Stable - provides confidence in daily activities</li><li>Proven Long-Term Results - patients trust it</li><li>High Patient Satisfaction - excellent outcomes</li></ul>`,
  },
  ageDetail: {
    title: "Age & Activity Level",
    parent: "chooseImplant",
    image: "https://images.unsplash.com/photo-1579154204601-01d82f3b80c8?w=600&h=400&fit=crop&q=80",
    content: `<h3 style="color: #2D8C7F; margin-bottom: 1rem;">Different Needs at Different Ages</h3><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">Younger, Active Patients</h4><ul style="list-style: none; padding: 0;"><li>Need implants that handle extensive movement</li><li>Require high strength and durability</li><li>Benefit from high-flexion designs</li><li>May need sports-specific options</li></ul><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">Older Patients</h4><ul style="list-style: none; padding: 0;"><li>Need comfortable, stable implants</li><li>Focus on daily living activities</li><li>Benefit from proven, standard designs</li></ul>`,
  },
  severityDetail: {
    title: "Severity of Knee Damage",
    parent: "chooseImplant",
    image: "https://images.unsplash.com/photo-1631217314830-4d4b2f32c147?w=600&h=400&fit=crop&q=80",
    content: `<h3 style="color: #2D8C7F; margin-bottom: 1rem;">Assessment of Knee Condition</h3><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">Treatment Options Based on Severity</h4><ul style="list-style: none; padding: 0;"><li><strong>Mild Damage:</strong> Partial replacement may be sufficient</li><li><strong>Moderate Damage:</strong> Total replacement recommended</li><li><strong>Severe Damage:</strong> Specialized implant systems may be needed</li><li><strong>Very Complex Cases:</strong> Custom or revision approaches</li></ul>`,
  },
  boneDetail: {
    title: "Bone Quality & Alignment",
    parent: "chooseImplant",
    image: "https://images.unsplash.com/photo-1576091160550-112173f7f869?w=600&h=400&fit=crop&q=80",
    content: `<h3 style="color: #2D8C7F; margin-bottom: 1rem;">Structural Assessment</h3><p>The strength and alignment of your bones are critical for successful knee implant placement and long-term durability.</p><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">What Dr. Nishant Checks</h4><ul style="list-style: none; padding: 0;"><li>Bone Strength - needed to support the implant</li><li>Knee Alignment - whether knee bows inward or outward</li><li>Ligament Condition - damaged or intact ligaments</li></ul>`,
  },
  lifestyleDetail: {
    title: "Lifestyle & Daily Activity",
    parent: "chooseImplant",
    image: "https://images.unsplash.com/photo-1579154204601-01d82f3b80c8?w=600&h=400&fit=crop&q=80",
    content: `<h3 style="color: #2D8C7F; margin-bottom: 1rem;">Activity-Specific Implant Choices</h3><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">Patients Who Benefit from High-Flexion Implants</h4><ul style="list-style: none; padding: 0;"><li>Sit cross-legged frequently</li><li>Climb stairs regularly</li><li>Participate in sports or fitness</li><li>Maintain active lifestyle</li><li>Squat or deep knee bending regularly</li></ul>`,
  },
  materialDetail: {
    title: "Implant Material & Technology",
    parent: "chooseImplant",
    image: "https://images.unsplash.com/photo-1631217314830-4d4b2f32c147?w=600&h=400&fit=crop&q=80",
    content: `<h3 style="color: #2D8C7F; margin-bottom: 1rem;">Advanced Materials & Engineering</h3><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">Implant Materials</h4><div style="background: #f7f9f8; padding: 1rem; border-radius: 8px; margin-bottom: 1rem;"><h5 style="color: #2D8C7F;">Metal Components</h5><p>Titanium or cobalt-chromium alloys provide strength and durability.</p></div><div style="background: #f7f9f8; padding: 1rem; border-radius: 8px;"><h5 style="color: #2D8C7F;">Plastic Components</h5><p>Medical-grade polyethylene creates a smooth, durable surface.</p></div>`,
  },
  beforeDetail: {
    title: "Before Surgery - Preparation",
    parent: "beforeAfter",
    image: "https://images.unsplash.com/photo-1576091160550-112173f7f869?w=600&h=400&fit=crop&q=80",
    content: `<h3 style="color: #2D8C7F; margin-bottom: 1rem;">Getting Ready for Success</h3><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">Pre-Surgery Steps</h4><ul style="list-style: none; padding: 0;"><li><strong>Medical Evaluation:</strong> Complete physical examination</li><li><strong>Laboratory Tests:</strong> Blood tests, diabetes screening, urine sample</li><li><strong>Medication Review:</strong> Assess impact of current medications</li><li><strong>Dental Evaluation:</strong> Complete dental work before surgery</li><li><strong>Urinary Evaluation:</strong> Test for urinary infections</li></ul>`,
  },
  procedureDetail: {
    title: "The Surgical Procedure",
    parent: "beforeAfter",
    image: "https://images.unsplash.com/photo-1579154204601-01d82f3b80c8?w=600&h=400&fit=crop&q=80",
    content: `<h3 style="color: #2D8C7F; margin-bottom: 1rem;">What Happens During Surgery</h3><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">The Four Basic Steps</h4><div style="background: #f7f9f8; padding: 1rem; border-radius: 8px; margin-bottom: 1rem;"><h5 style="color: #2D8C7F;">1. Prepare the Skeleton</h5><p>Remove damaged cartilage and bone from femur and tibia.</p></div><div style="background: #f7f9f8; padding: 1rem; border-radius: 8px; margin-bottom: 1rem;"><h5 style="color: #2D8C7F;">2. Arrange Metal Implants</h5><p>Metal components replace removed bone and cartilage.</p></div><div style="background: #f7f9f8; padding: 1rem; border-radius: 8px; margin-bottom: 1rem;"><h5 style="color: #2D8C7F;">3. Recondition the Kneecap</h5><p>Undersurface of kneecap is resurfaced with plastic button.</p></div><div style="background: #f7f9f8; padding: 1rem; border-radius: 8px;"><h5 style="color: #2D8C7F;">4. Place a Separator</h5><p>Medical-grade plastic spacer creates smooth sliding surface.</p></div><p><strong>Duration:</strong> 1-2 hours typically</p>`,
  },
  recoveryDetail: {
    title: "Recovery & Rehabilitation",
    parent: "beforeAfter",
    image: "https://images.unsplash.com/photo-1631217314830-4d4b2f32c147?w=600&h=400&fit=crop&q=80",
    content: `<h3 style="color: #2D8C7F; margin-bottom: 1rem;">Your Path Back to Normal</h3><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">Recovery Timeline</h4><ul style="list-style: none; padding: 0;"><li><strong>Hospital Stay:</strong> 3-5 days</li><li><strong>First 2 Weeks:</strong> Rest, ice, pain management, gentle exercises</li><li><strong>2-6 Weeks:</strong> Can perform daily activities with support</li><li><strong>3 Months:</strong> Most pain resolved, improved mobility</li><li><strong>6 Months:</strong> Significant functional improvement</li><li><strong>12 Months:</strong> Full recovery and adaptation</li></ul><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">Physical Therapy</h4><p>A physical therapist will guide you through exercises to maintain joint flexibility, restore muscle strength, improve balance, and return to normal activities.</p>`,
  },
  complicationsDetail: {
    title: "Possible Complications",
    parent: "beforeAfter",
    image: "https://images.unsplash.com/photo-1576091160550-112173f7f869?w=600&h=400&fit=crop&q=80",
    content: `<h3 style="color: #2D8C7F; margin-bottom: 1rem;">Understanding Risks</h3><p>While complications are rare (less than 2%), it's important to be aware of what to watch for after surgery.</p><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">Possible Complications</h4><ul style="list-style: none; padding: 0;"><li><strong>Infection:</strong> In wound or deep around prosthesis</li><li><strong>Blood Clots:</strong> In leg veins</li><li><strong>Implant Problems:</strong> Wear down and looseness</li><li><strong>Persistent Pain:</strong> May last several days</li><li><strong>Nerve/Blood Vessel Damage:</strong> Uncommon but possible</li></ul><h4 style="color: #1f6860; margin: 1.5rem 0 0.5rem;">When to Call Dr. Nishant</h4><ul style="list-style: none; padding: 0;"><li>Sudden increase in pain</li><li>Signs of infection (fever, redness, drainage)</li><li>Severe swelling</li><li>Knee giving way or instability</li><li>Chest pain or shortness of breath</li></ul>`,
  },
};
